---
name: Build dist

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed


jobs: 
  Build-dist:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Install dependancies
        run: npm install

      - name: Build to dist
        run: npm run build
 
      - name: List files
        run: ls ${{ github.workspace }}

