---
name: Build dist

on:
  workflow_dispatch:
  release:
    types: [released]


jobs: 
  Build-dist:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Build to dist
        run: npm run build
 
      - name: Build project image
        run: |
          podman build . -t ${{ github.event.repository.name }}

      - name: login to docker
        run: |
          echo ${{ secrets.docker_token }} | podman login docker.io -u ${{ vars.docker_user }} --password-stdin

      - name: Publish project image
        run: |
          ID=$(podman images ${{ github.event.repository.name }} -q)
          podman image push $ID docker.io/${{ vars.docker_user}}/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}

      - name: logout 
        run: |
          podman logout
