---
name: Build dist

on:
  workflow_dispatch:
  release:
    types: [released]
  #  pull_request_target:
  #    branches:
  #      - main
  #    types:
  #      - closed


jobs: 
  Build-dist:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      project_name: ${{github.event.repository.name}}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Build to dist
        run: npm run build
 
      - name: Build project image
        run: |
          podman build . -t ${{ github.event.repository.name }}

      - name: login to docker
        run: |
          podman login docker.io -u ${{ vars.docker_user }} -p ${{ secrets.docker_token }}

      - name: Publish project image
        run: |
          ID=$(podman images $project_name -q)
          podman image push $ID docker.io/${{ vars.docker_user}}/$project_name${{ github.ref_name }}

      - name: logout 
        run: |
          podman logout
