---
name: Build Dev

on:
  pull_request_target:
    branches:
      - dev
    types:
      - closed

jobs: 
  Build-dist:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Build to dist
        run: npm run build
 
      - name: Build project image
        run: |
          podman build . -t ${{ github.event.repository.name }}_dev:

      - name: login to docker
        run: |
          echo ${{ secrets.docker_token }} | podman login docker.io -u ${{ vars.docker_user }} --password-stdin

      - name: Publish project image
        run: |
          ID=$(podman images ${{ github.event.repository.name }}_dev -q)
          podman image push $ID docker.io/${{ vars.docker_user}}/${{ github.event.repository.name }}_dev:${{ github.sha }}

      - name: logout 
        run: |
          podman logout

